version: '3.8'
services:
  ai-search:
    build: .
    container_name: ai_search_service
    network_mode: host
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PORT
      - MYSQL_CHARSET
      - MYSQL_COLLATION
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Все параметры теперь берутся из .env файла 